### PR TITLE
Development

### PR DESCRIPTION
**Pull request by AlejoCode**
Request validation for this project by hand of the designates TSE

We will be waiting the feedback

Thank you so much

### CODE REVIEW

**Comment by rvvergara** [comment]
Hi guys,

Awesome looking Mint clone! :) Here are, however, some changes I'd like you to make:

1. You don't have a README.md -> Kindly make one and make sure it shows the Project Title, your respective names and links to your Github profiles, a short description of the project and a link to the Live Demo (use raw.githack.com or github pages for this whichever you prefer).

2. Directory structure -> Kindly put your css file into a css/ folder under an assets/ folder. This is not a big project so this shouldn' be a big deal but it's great to get used to having an organized directory structure early on 

3. Minor HTML validator issue -> Run your index.html code into the validator.w3.org tool. There are 2 minor errors that you can fix :) Moving forward it is a good practice to use this tool prior to submitting the project

4. CSS Dry -> While all of us are guilty of this, no matter how long we've been coding, it's nonetheless important to avoid code repetitions. I know working on CSS always makes us vulnerable to repeating some lines. In this case, for example, the line `font-size: 12px` appeared in 5 lines (20, 114, 191, 214 and 225). You can reduce this into one line by calling all the selectors at once (separated by a comma) or creating a class for this particular style and using it into those elements whose fontsize you'd like to be 12px.

That's it for now. And yeah, once you finish working on these just submit another code review request. 

Ryan

**Comment by BalintMendli** [comment]
Thanks for the detailed feedback. Requested changes made.

**Comment by rvvergara** [comment]
Awesome guys! You did great.. For that ...

# :+1: 

You may now merge this branch to master and fill up the Project Completion Form :)

**Comment by AlejoCode** [comment]
Thank you for all your help and we are making the merge right now 

:man_technologist:

**Pull request merged**
